### ISSUE TITLE
Fix Reading the request body timed out due to data arriving too slowly. See MinRequestBodyDataRate.

### ISSUE THREAD

**Issue by ipdae** [planetarium/ArenaService#29]
![image](https://github.com/user-attachments/assets/f7d51b84-36ad-4742-b2da-c0fc989e53c3)

**Comment by Atralupus** [comment]
https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits.minrequestbodydatarate?view=aspnetcore-9.0

**Comment by Atralupus** [comment]
Defaults to 240 bytes/second with a 5 second grace period.
